##################################################
# 	required
##################################################

# this can be a company/brand or product namespace under which all content lives
# typically, this is the github user or org where the source of this collection
# will live
namespace: "{{ cookiecutter.collection_namespace }}"

# the designation of this specific collection
name: "{{ cookiecutter.collection_name }}"

# semantic versioning compliant version designation
version: "{{cookiecutter.collection_version }}"

# a list of the collection's content authors: 'Full Name <email> (http://site) @nicks:irc/im/site#channel'
authors:
  - "{{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>"


# short summary of the collection
description: "{{ cookiecutter.collection_description }}"

# a valid SPDX license identifier https://spdx.org/licenses/
license: "{{ cookiecutter.collection_spdx_license }}"

# list of keywords you want to associate the collection with for indexing/search systems
tags:

# list of dependencies, other collections this collection requires to be installed for it to be usable
dependencies:

##################################################
# 	links
##################################################

# url of originating SCM repository
repository:

# url to online docs
documentation:

# homepage of the collection/project
homepage:

# issue tracker url
issues:
